/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.mindfusion.charting.Axis;
import com.mindfusion.charting.FunctionSeries;
import com.mindfusion.charting.GridType;
import com.mindfusion.charting.swing.LineChart;
import com.mindfusion.drawing.DashStyle;
import com.mindfusion.drawing.SolidBrush;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.geom.RoundRectangle2D;
import java.beans.Statement;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.*;
import java.io.File;
//import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.sql.Statement;
import java.io.File;
//import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javaapplication1.ModelData;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;

//import java.sql.Statement;
/**
 *
 * @author anna
 */
public class menu extends javax.swing.JFrame {
 private static final String JDBC_URL = "jdbc:mysql://localhost:3306/ahmad";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "W@2915djkq#";
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private String companyName;

    /**
     
     * Creates new form menu


    
    
    
    // Other methods and components of your menu class...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    public menu() throws SQLException, IOException {
       initComponents();
        populateCompanyComboBox();
         createAndShowChart();
         java.sql.Connection con;
        java.sql.Statement st;
        ResultSet rs;
        
        
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
    st = con.createStatement();
    rs = st.executeQuery("SELECT count(arvan_hoyr) FROM sudalgaa where arvan_hoyr='Тийм'");
    if (rs.next()) {
        arvan_hoyr1.setText(rs.getString(1));
    }
} catch (ClassNotFoundException | SQLException ex) {
    ex.printStackTrace();
}

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
    st = con.createStatement();
    rs = st.executeQuery("SELECT count(arvan_gurav) FROM sudalgaa where arvan_gurav='Тийм'");
    if (rs.next()) {
        arvan_gurav1.setText(rs.getString(1));
    }
} catch (ClassNotFoundException | SQLException ex) {
    ex.printStackTrace();
}

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
    st = con.createStatement();
    rs = st.executeQuery("SELECT count(odoo_ajillaj) FROM sudalgaa where odoo_ajillaj='Тийм'");
    if (rs.next()) {
        odoo_ajillaj1.setText(rs.getString(1));
    }
} catch (ClassNotFoundException | SQLException ex) {
    ex.printStackTrace();
}

        
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad","root","W@2915djkq#");
        st=con.createStatement();
        rs=st.executeQuery("SELECT COUNT(*) AS rowCount FROM sudalgaa;");
        if(rs.next()){
           jLabel9.setText(rs.getString(1));
        }
        }catch(ClassNotFoundException ex){
        }
       
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());
        jPanel6 = new RoundJPanel(214, 76); // Set background color as needed
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ahmad1 = new javax.swing.JLabel();
        companyComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        arvan_hoyr1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        arvan_gurav1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        odoo_ajillaj1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\anna\\Desktop\\Arig-Gal_logo12.png")); // NOI18N

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());
        jPanel2 = new RoundJPanel(214, 76); // Set background color as needed
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_50px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("НҮҮР");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ubisoft_50px_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("БАЙГУУЛЛАГУУД");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());
        jPanel9 = new RoundJPanel(214, 76); // Set background color as needed
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Plus_50px.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("БҮРТГЭЛ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        panel.setLayout(new java.awt.BorderLayout());

        companyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Кашмер Холдинг", "Мон-Мяндас", "Хавт шонхор", "Эвсэг-Од", "Говийн мяндас", "Тансаг ширээс", "Эвсэг ХХК", " " }));
        companyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Нийт");

        jLabel10.setText("Бүх ахмадууд");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyComboBox, 0, 208, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ahmad1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ahmad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(companyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.setPreferredSize(new java.awt.Dimension(220, 160));

        jLabel11.setText("Нийт");

        jLabel14.setText("2012 өмнө тэтгэвэрт гарсан");

        jLabel15.setText(" ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arvan_hoyr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arvan_hoyr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(52, 52, 52))
        );

        jPanel12.setPreferredSize(new java.awt.Dimension(220, 160));

        jLabel12.setText("Нийт");

        jLabel16.setText("2013 хойш тэтгэвэрт гарсан");

        jLabel17.setText(" ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arvan_gurav1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(arvan_gurav1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(57, 57, 57))
        );

        jPanel13.setPreferredSize(new java.awt.Dimension(220, 160));

        jLabel13.setText("Нийт");

        jLabel18.setText("Одоо компанид ажиллаж байгаа");

        jLabel19.setText(" ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odoo_ajillaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(odoo_ajillaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(58, 58, 58))
        );

        jLabel20.setText("\"Ариг гал\" ХК-ахмадуудын судалгаа хэвлэх");

        generateButton.setText("Хэвлэх");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(57, 57, 57))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(generateButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1640, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        setColor(jPanel6);
        resetColor(jPanel2);
        resetColor(jPanel9);
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        setColor(jPanel2);
        resetColor(jPanel6);
        resetColor(jPanel9);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        setColor(jPanel9);
        resetColor(jPanel6);
        resetColor(jPanel2);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        setColor(jPanel6);
        resetColor(jPanel2);
        resetColor(jPanel9);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
        resetColor(jPanel6);
        resetColor(jPanel9);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jPanel10.setVisible(true);
        jPanel8.setVisible(false);
        jPanel3.setVisible(false);
                                      
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        jPanel10.setVisible(false);
        jPanel8.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        jPanel10.setVisible(false);
        jPanel8.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void companyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyComboBoxActionPerformed
        // TODO add your handling code here:
        updateStatistics();
    }//GEN-LAST:event_companyComboBoxActionPerformed
private static final String MONGOLIAN_FONT_PATH = "path/to/your/mongolian/font.ttf"; // Replace with the actual path to your Mongolian font file
    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
                                             try {
        Document document = new Document();

        PdfWriter.getInstance(document, new FileOutputStream("hevleh.pdf"));

        document.open();

        // Add title with centered alignment1
         BaseFont mongolianFont = BaseFont.createFont(MONGOLIAN_FONT_PATH, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        Font titleFont = new Font(mongolianFont, 18, Font.BOLD);
        Paragraph title = new Paragraph("Arig gal HK-iin ahmaduudiin sudalgaa", FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD));
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        // Format the date string in Mongolian locale with right alignment
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", new Locale("mn"));
        String mongolianDate = dateFormat.format(new Date());
        Paragraph dateParagraph = new Paragraph(mongolianDate);
        dateParagraph.setAlignment(Element.ALIGN_RIGHT);
        document.add(dateParagraph);

        // Add the table to the document
        PdfPTable table = new PdfPTable(6);
        // Set table alignment to center
        table.setHorizontalAlignment(Element.ALIGN_CENTER);

        // Add table header
        Font tableHeaderFont = new Font(mongolianFont, 12, Font.BOLD);
        table.addCell(new PdfPCell(new Phrase("D/d (Deputy Number)", tableHeaderFont)));
        table.addCell(new PdfPCell(new Phrase("Company", tableHeaderFont)));
        table.addCell(new PdfPCell(new Phrase("All Ajilchid", tableHeaderFont)));
        table.addCell(new PdfPCell(new Phrase("2012", tableHeaderFont)));
        table.addCell(new PdfPCell(new Phrase("2013", tableHeaderFont)));
        table.addCell(new PdfPCell(new Phrase("Odoo", tableHeaderFont)));

        // Add table data using a loop (assuming you want to loop from 1 to 100)
 // Assuming you want to start counting from 1

    // Fetch data for the current company from the database
 

    // Replace the following lines with your actual data retrieval logic based on each company
    int i = 0;
while (i < 7) {
    // Fetch data for the current company from the database
        
        String deputyNumber = String.valueOf(i + 1);
    String companyName = companyComboBox.getItemAt(i);
    
    // Retrieve data for the current company

    String ahmadData = "";
    String label15Data = "";
    String label17Data = "";
    String label19Data = "";

    // Customize data retrieval based on the selected company
    if ("Кашмер Холдинг".equals(companyName)) {
        // Data retrieval logic for "Кашмер Холдинг"
        ahmadData = getAhmadDataForCompany1();
        label15Data = getLabel15DataForCompany1();
        label17Data = getLabel17DataForCompany1();
        label19Data = getLabel19DataForCompany1();
    } else if ("Мон-Мяндас".equals(companyName)) {
        // Data retrieval logic for "Мон-Мяндас"
        ahmadData = getAhmadDataForCompany2();
        label15Data = getLabel15DataForCompany2();
        label17Data = getLabel17DataForCompany2();
        label19Data = getLabel19DataForCompany2();
    } else if ("Хавт шонхор".equals(companyName)) {
        // Data retrieval logic for "Хавт шонхор"
        ahmadData = getAhmadDataForCompany3();
        label15Data = getLabel15DataForCompany3();
        label17Data = getLabel17DataForCompany3();
        label19Data = getLabel19DataForCompany3();
    } else if ("Эвсэг-Од".equals(companyName)) {
        // Data retrieval logic for "Эвсэг-Од"
        ahmadData = getAhmadDataForCompany4();
        label15Data = getLabel15DataForCompany4();
        label17Data = getLabel17DataForCompany4();
        label19Data = getLabel19DataForCompany4();
    } else if ("Говийн мяндас".equals(companyName)) {
        // Data retrieval logic for "Говийн мяндас"
        ahmadData = getAhmadDataForCompany5();
        label15Data = getLabel15DataForCompany5();
        label17Data = getLabel17DataForCompany5();
        label19Data = getLabel19DataForCompany5();
    } else if ("Тансаг ширээс".equals(companyName)) {
        // Data retrieval logic for "Тансаг ширээс"
        ahmadData = getAhmadDataForCompany6();
        label15Data = getLabel15DataForCompany6();
        label17Data = getLabel17DataForCompany6();
        label19Data = getLabel19DataForCompany6();
    } else if ("Эвсэг ХХК".equals(companyName)) {
        // Data retrieval logic for "Эвсэг ХХК"
        ahmadData = getAhmadDataForCompany7();
        label15Data = getLabel15DataForCompany7();
        label17Data = getLabel17DataForCompany7();
        label19Data = getLabel19DataForCompany7();
    }
    // Add more conditions for other companies...

    
    Font tableCellFont = new Font(mongolianFont, 10);
            table.addCell(new PdfPCell(new Phrase(deputyNumber, tableCellFont)));
            table.addCell(new PdfPCell(new Phrase(companyName, tableCellFont)));
            table.addCell(new PdfPCell(new Phrase(ahmadData, tableCellFont)));
            table.addCell(new PdfPCell(new Phrase(label15Data, tableCellFont)));
            table.addCell(new PdfPCell(new Phrase(label17Data, tableCellFont)));
            table.addCell(new PdfPCell(new Phrase(label19Data, tableCellFont)));

    i++;
}





        // Add a row for "niit"
        table.addCell("");
        table.addCell("niit"); // Add data for the Company column (Replace with actual data)
        table.addCell(jLabel9.getText()); // Add data for the All Ajilchid column (Replace with actual data)
        table.addCell(arvan_hoyr1.getText()); // Add data for the 2012 column (Replace with actual data)
        table.addCell(arvan_gurav1.getText()); // Add data for the 2013 column (Replace with actual data)
        table.addCell(odoo_ajillaj1.getText()); // Add data for the Odoo column (Replace with actual data)

        document.add(table);

        // Create a list and add items to it
        com.itextpdf.text.List list = new com.itextpdf.text.List();
        // Set list alignment to right

        list.add(new ListItem("Negtgesen: KH HHK HNA                                                                                B.Baasandorj"));
        list.add(new ListItem("Taniltsan:Ahmadiin asuudal hariutssan ajiltan                                                  J.Baasanjav"));

        // Add the list to the document
        document.add(list);

        document.close();
 
        JOptionPane.showMessageDialog(null, "Hadgalagdlaa");
        openPDFFile("C:\\Users\\anna\\Documents\\NetBeansProjects\\JavaApplication1\\hevleh.pdf");
    } catch (DocumentException | IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e.getMessage());
    }



    }//GEN-LAST:event_generateButtonActionPerformed
    void setColor(JPanel panel){
        panel.setBackground(new Color(102,255,102));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(242,242,242));
    }
    
    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    try {
        // Use the system default look and feel
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        e.printStackTrace();
    }
    
        
                       	                   
	                    	                
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                new menu().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    });
    
    
    
}
  private void showChartButtonActionPerformed(ActionEvent evt) {
        createAndShowChart();
    }

private void createAndShowChart() {
        String query = "SELECT tetgevert_garsan_on, COUNT(*) FROM medeelel GROUP BY tetgevert_garsan_on";

        try (java.sql.Connection connection = DriverManager.getConnection(JDBC_URL, USERNAME, PASSWORD);
             java.sql.Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(query)) {

            JDBCCategoryDataset dataset = new JDBCCategoryDataset(connection, query);
            dataset.executeQuery(query);

            JFreeChart chart = ChartFactory.createLineChart(
                    "Ахмадын судалгааны график",
                    "Он",
                    "Нийт ахмадийн тоо",
                    dataset,
                    PlotOrientation.VERTICAL,
                    false,
                    true,
                    true
            );

            LineAndShapeRenderer renderer = new LineAndShapeRenderer();
            chart.getCategoryPlot().setRenderer(renderer);

            ChartPanel chartPanel = new ChartPanel(chart);
            panel.removeAll();
            panel.add(chartPanel, BorderLayout.CENTER);
            panel.revalidate();
            panel.repaint();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }


private void populateCompanyComboBox() throws IOException, SQLException {
    try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#")) {
        try (java.sql.Statement st = con.createStatement()) {
            try (ResultSet rs = st.executeQuery("SELECT company, COUNT(*) AS count FROM sudalgaa GROUP BY company")) {
                while (rs.next()) {
                    String companyName = rs.getString("company");
                    int count = rs.getInt("count");
                    String displayText = companyName + " (" + count + ")";
                    companyComboBox.addItem(displayText);
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Close resources (in reverse order of creation)
        if (con != null) {
            con.close();
        }
    }
}




    private void updateStatistics() {
        Object selectedCompanyItem = companyComboBox.getSelectedItem();

        if (selectedCompanyItem != null) {
            String selectedCompanyText = selectedCompanyItem.toString();
            String selectedCompany = selectedCompanyText.split("\\(")[0].trim();

            try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
                 PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM sudalgaa WHERE company = ?")) {

                preparedStatement.setString(1, selectedCompany);

                try (ResultSet rs = preparedStatement.executeQuery()) {
                    if (rs.next()) {
                        // Assuming ahmad1 is a JTextComponent where you want to display the count
                        ahmad1.setText(rs.getString(1));
                        
                    }

                    // Update other statistics as needed
                }
            } catch (SQLException ex) {
                ex.printStackTrace(); // Log or handle the exception more appropriately
            }
            try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
                 PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM sudalgaa WHERE company = ? AND arvan_hoyr = 'Тийм'")) {

                preparedStatement.setString(1, selectedCompany);

                try (ResultSet rs = preparedStatement.executeQuery()) {
                    if (rs.next()) {
                        // Assuming ahmad1 is a JTextComponent where you want to display the count
                        jLabel15.setText(rs.getString(1));
                        
                    }

                    // Update other statistics as needed
                }
            } catch (SQLException ex) {
                ex.printStackTrace(); // Log or handle the exception more appropriately
            }
            try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
                 PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM sudalgaa WHERE company = ? AND arvan_gurav = 'Тийм'")) {

                preparedStatement.setString(1, selectedCompany);

                try (ResultSet rs = preparedStatement.executeQuery()) {
                    if (rs.next()) {
                        // Assuming ahmad1 is a JTextComponent where you want to display the count
                        jLabel17.setText(rs.getString(1));
                        
                    }

                    // Update other statistics as needed
                }
            } catch (SQLException ex) {
                ex.printStackTrace(); // Log or handle the exception more appropriately
            }
            try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
                 PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM sudalgaa WHERE company = ? AND odoo_ajillaj = 'Тийм'")) {

                preparedStatement.setString(1, selectedCompany);

                try (ResultSet rs = preparedStatement.executeQuery()) {
                    if (rs.next()) {
                        // Assuming ahmad1 is a JTextComponent where you want to display the count
                        jLabel19.setText(rs.getString(1));
                        
                    }

                    // Update other statistics as needed
                }
            } catch (SQLException ex) {
                ex.printStackTrace(); // Log or handle the exception more appropriately
            }
        }
    }
    private String getDeputyNumberForCompany(String companyName) {
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
         PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM sudalgaa a_code")) {

        preparedStatement.setString(1, companyName);

        try (ResultSet rs = preparedStatement.executeQuery()) {
            if (rs.next()) {
                return rs.getString("a_code");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Log or handle the exception more appropriately
    }
    return "";
}
    private String getAhmadDataForCompany1() {
    return getCountForCompany("Кашмер Холдинг");
}

private String getLabel15DataForCompany1() {
    return getCountForCompanyWithCondition("Кашмер Холдинг", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany1() {
    return getCountForCompanyWithCondition("Кашмер Холдинг", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany1() {
    return getCountForCompanyWithCondition("Кашмер Холдинг", "odoo_ajillaj = 'Тийм'");
}

// Implement similar methods for other companies

private String getCountForCompany(String companyName) {
    return executeCountQuery("SELECT COUNT(*) FROM sudalgaa WHERE company = ?", companyName);
}

private String getCountForCompanyWithCondition(String companyName, String condition) {
    String sqlQuery = "SELECT COUNT(*) FROM sudalgaa WHERE company = ? AND " + condition;
    return executeCountQuery(sqlQuery, companyName);
}

private String executeCountQuery(String sqlQuery, String companyName) {
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ahmad", "root", "W@2915djkq#");
         PreparedStatement preparedStatement = connection.prepareStatement(sqlQuery)) {

        preparedStatement.setString(1, companyName);

        try (ResultSet rs = preparedStatement.executeQuery()) {
            if (rs.next()) {
                return rs.getString(1);
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Log or handle the exception more appropriately
    }
    return "";
}
private String getAhmadDataForCompany2() {
    return getCountForCompany("Мон-Мяндас");
}

private String getLabel15DataForCompany2() {
    return getCountForCompanyWithCondition("Мон-Мяндас", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany2() {
    return getCountForCompanyWithCondition("Мон-Мяндас", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany2() {
    return getCountForCompanyWithCondition("Мон-Мяндас", "odoo_ajillaj = 'Тийм'");
}
private String getAhmadDataForCompany3() {
    return getCountForCompany("Хавт шонхор");
}

private String getLabel15DataForCompany3() {
    return getCountForCompanyWithCondition("Хавт шонхор", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany3() {
    return getCountForCompanyWithCondition("Хавт шонхор", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany3() {
    return getCountForCompanyWithCondition("Хавт шонхор", "odoo_ajillaj = 'Тийм'");
}
private String getAhmadDataForCompany4() {
    return getCountForCompany("Эвсэг-Од");
}

private String getLabel15DataForCompany4() {
    return getCountForCompanyWithCondition("Эвсэг-Од", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany4() {
    return getCountForCompanyWithCondition("Эвсэг-Од", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany4() {
    return getCountForCompanyWithCondition("Эвсэг-Од", "odoo_ajillaj = 'Тийм'");
}
private String getAhmadDataForCompany5() {
    return getCountForCompany("Говийн мяндас");
}

private String getLabel15DataForCompany5() {
    return getCountForCompanyWithCondition("Говийн мяндас", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany5() {
    return getCountForCompanyWithCondition("Говийн мяндас", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany5() {
    return getCountForCompanyWithCondition("Говийн мяндас", "odoo_ajillaj = 'Тийм'");
}
private String getAhmadDataForCompany6() {
    return getCountForCompany("Тансаг ширээс");
}

private String getLabel15DataForCompany6() {
    return getCountForCompanyWithCondition("Тансаг ширээс", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany6() {
    return getCountForCompanyWithCondition("Тансаг ширээс", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany6() {
    return getCountForCompanyWithCondition("Тансаг ширээс", "odoo_ajillaj = 'Тийм'");
}
private String getAhmadDataForCompany7() {
    return getCountForCompany("Эвсэг ХХК");
}

private String getLabel15DataForCompany7() {
    return getCountForCompanyWithCondition("Эвсэг ХХК", "arvan_hoyr = 'Тийм'");
}

private String getLabel17DataForCompany7() {
    return getCountForCompanyWithCondition("Эвсэг ХХК", "arvan_gurav = 'Тийм'");
}

private String getLabel19DataForCompany7() {
    return getCountForCompanyWithCondition("Эвсэг ХХК", "odoo_ajillaj = 'Тийм'");
}

    private void generateReportButtonActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
//C:\\Users\\anna\\Documents\\NetBeansProjects\\JavaApplication1\\hevleh.pdf
    private void openPDFFile(String filePath) {
    try {
        File file = new File(filePath);
        if (file.exists()) {
            Desktop.getDesktop().open(file);
        } else {
            System.out.println("File not found: " + filePath);
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}


            
    

class RoundJTextField extends JTextField {
    private Shape shape;

    public RoundJTextField(int size) {
        super(size);
        setOpaque(false); // As suggested by @camickr
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(getBackground());
        g.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
        super.paintComponent(g);
    }

    @Override
    protected void paintBorder(Graphics g) {
        g.setColor(getForeground());
        g.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
    }

    @Override
    public boolean contains(int x, int y) {
        if (shape == null || !shape.getBounds().equals(getBounds())) {
            shape = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
        }
        return shape.contains(x, y);
    }
}
class RoundJPanel extends JPanel {
    private Shape shape;

    public RoundJPanel(int width, int height) {
        setPreferredSize(new Dimension(width, height));
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (shape == null || !shape.getBounds().equals(getBounds())) {
            shape = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(getBackground());
        g2d.fill(shape);
        super.paintComponent(g);
    }

    @Override
    protected void paintBorder(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor((Color.RED));
        g2d.draw(shape);
    }

        protected RoundJPanel()
	{
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setSize(650, 400);
		setTitle("Java Swing Library for Charts and Gauges: FunctionSeries");
		
		getContentPane().add(initializeChart(), BorderLayout.CENTER);
		
	}

        private Component initializeChart() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ahmad1;
    private javax.swing.JLabel arvan_gurav1;
    private javax.swing.JLabel arvan_hoyr1;
    private javax.swing.JComboBox<String> companyComboBox;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel odoo_ajillaj1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}